config/routes.rb
Rails.application.routes.draw do

  # get 'students/index'

  resources :assignments do
    resources :submissions, except: [:index]
  end

  resources :sources

  resources :dashboard, only: [:index]

  devise_for :instructors
  devise_for :students

  resources :students, only: [:index, :show]

  namespace :instructor do
    resources :assignments do
      resources :submissions, only: [:index, :show, :update, :destroy]
    end
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="jumbotron text-left">
  <div class="name">ClassTime</div>
  <div class="tagline">A Learning Management System for College Courses</div>
  
  <% unless current_student || current_instructor %>
    <div class="login-links">
      <p class="login">Log In</p>
      <div class="button-margins">
        <%= link_to "Student", new_student_session_path, class: "btn btn-primary btn-margins btn-lg" %>
        <%= link_to "Instructor", new_instructor_session_path, class: "btn btn-warning btn-margins btn-lg" %>
      </div>
      </br>

      <p class="login">Sign Up</p>
      <div class="button-margins">
        <%= link_to "Student", new_student_registration_path, class: "btn-margins" %>
        <%= link_to "Instructor", new_instructor_registration_path, class: "btn-margins" %>
      </div>
    </div>
  <% end %>
</div>