config/routes.rb
Rails.application.routes.draw do

  # get 'students/index'

  resources :assignments do
    resources :submissions, except: [:index]
  end

  resources :sources

  resources :dashboard, only: [:index]

  devise_for :instructors
  devise_for :students

  resources :students, only: [:index, :show]

  namespace :instructor do
    resources :assignments do
      resources :submissions, only: [:index, :show, :update, :destroy]
    end
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClassTime</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <!-- <li><%# link_to "ClassTime", root_path %></li> -->
        <% if current_student %>
          <li><%= link_to "My Page", student_path(current_student) %>
        <% end %>
        <% if current_student || current_instructor %>
          <li><%= link_to "Sources", sources_path %></li>
          <li><%= link_to "Assignments", assignments_path %></li>
        <% end %>
        <% if current_instructor %>
          <li><%= link_to "Gradebook", students_path %></li>
        <% end %>

        <div class="text-right top-buffer">
          <% if instructor_signed_in? %>
            Signed in as: <strong><%= current_instructor.firstname + " " + current_instructor.lastname %></strong> |
            <%= link_to 'Edit profile', edit_instructor_registration_path, :class => 'navbar-link' %> -
            <%= link_to "Sign Out", destroy_instructor_session_path, method: :delete, :class => 'navbar-link' %>
          <% elsif student_signed_in? %>
            Signed in as: <strong><%= current_student.firstname + " " + current_student.lastname %></strong> |
            <%= link_to 'Edit profile', edit_student_registration_path, :class => 'navbar-link' %> -
            <%= link_to "Sign Out", destroy_student_session_path, method: :delete, :class => 'navbar-link' %>
          <% end %>
        </div>
      </ul>

      <!-- <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <%elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %> -->

      <%= yield %>
    </div>
  </body>
</html>